config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'home/index' # bundle exec rails g controller home indexすると自動で追加される
  get 'index' => 'home#index' # localhost:3000/index や localhost:3000/index.html は home#index に飛ばす

  devise_for :users

  get 'items/current_user_id' => 'items#current_user_id'

  get 'items/index_by_user' => 'items#index_by_user'
  get 'items/show_recipes' => 'items#show_recipes'
  resources :items

  get 'freshnesses/freshness_by_name' => 'freshnesses#freshness_by_name'
  resources :freshnesses

end

app/models/item.rb
class Item < ActiveRecord::Base
  # usersと多対多の関係になるのをやめたためコメントアウト
  # has_many :user_items
  # has_many :users, :through => :user_items
  belongs_to :user

  # carrierwave用
  mount_uploader :icon, IconUploader
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.js 部分テンプレートを呼び出したいときはこちら
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.js # show.js.erb が実行される
      format.json { render :show, status: :ok, location: @item }
    end
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
    # editでは，他のアクションと同じようにeditページに遷移するとき以下のレンダリング処理が発生する．
    # editページでsubmitが押されたときのアクションはupdateである．
    respond_to do |format|
      format.html { render :show }
      format.js # edit.js.erb が実行される．link_to で :remote => true の場合はこれになる
      format.json { render :show, status: :ok, location: @item }
    end
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new#(item_params)

    # jsonとして渡ってきたパラメターをパースして，新規作成したitemに設定
    @item.title = params['item']['title']
    @item.user_id = params['item']['user_id']
    @item.start = params['item']['start']
    @item.end = params['item']['end']
    @item.allDay = params['item']['all_day']

    # upload_file = image_params[:file]
    # image = {}
    # if upload_file != nil
    #   image[:filename] = upload_file.original_filename
    #   image[:file] = upload_file.read
    # end
    # @image = Image.new(image)
    # if @image.save
    #   flash[:success] = "画像を保存しました。"
    #   # redirect_to @image
    # else
    #   flash[:error] = "保存できませんでした。"
    # end

    respond_to do |format|
      if @item.save
        # format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.html { redirect_to @item }
        format.json { render :show, status: :created, location: @item }
        #format.html { redirect_to edit_item_path(@item.id) }
        #format.json { redirect_to edit_item_path(@item.id) }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        # format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.html { redirect_to @item }
        format.js # update.js.erb が実行される．submit で :remote => true の場合はこれになる
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      # format.html { redirect_to index_url, notice: 'Item was successfully destroyed.' }
      format.html { redirect_to index_url }
      format.js # destroy.js.erb が実行される．link_to で :remote => true の場合はこれになる
      format.json { head :no_content }
    end
  end


  #=================================================================================================================================================
  # ユーザidにもとづいて所持商品一覧を取得してjsonで返す．fullcalender用
  # GET /items/index_by_user.json
  def index_by_user
    # current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド
    @items = Item.where(:user_id => current_user.id);
    respond_to do |format|
      # 拡張子がjsonで来た場合のみ応答
      format.json { render :json => @items }
    end
    # 拡張子で何が来ようが拡張子が無かろうがjsonで返す
    # render :json => @items
  end

  # 現在ログインしているユーザのidを返す．
  # current_userメソッドは，deviseが提供している現在のユーザ情報を返すヘルパメソッド
  # GET /items/current_user_id
  def current_user_id
    respond_to do |format|
      # 拡張子がjsonで来た場合のみ応答
      format.json { render :json => current_user.id }
    end
  end

  def show_recipes
    array = Array.new
    # 複数渡せるようにarrayにしているが，フロントが複数選択に未対応のためとりあえず1個だけクエリを渡す．
    array << params[:name]
    @recipes = acquire_recommended_recipes(array);
    #puts @recipes
    respond_to do |format|
      format.js # show_recipes.js.erb が実行される
    end
  end


  #=================================================================================================================================================
  # テキストファイルに落としたメールをパースしてデータを登録
  def recvmail(now_date)
    #mail = Mail.read("app/controllers/tmp/#{now_date}_mail.txt")
    #puts [mail.envelope_from, mail.body.decoded]

    begin
      # 検索用正規表現を準備
      reg1=/.?商品名称.?[\s]*(.+)[\s]([0-9]+.*)/
      reg2=/.*数量.?([0-9]+).*/
      reg3=/.*注文者.?[\s]*(.+)[\s]+様/

      # ファイルを取得
      # df="./tmp/mail.txt"
      df="./tmp/#{now_date}_mail.txt"
      file=File.new(df)

      # 全データを入れるハッシュを作成
      #if file
      @parsed_items = Hash.new
      # ファイルをパース
      while line=file.gets
        # 注文者を取得
        # if line.force_encoding("UTF-8").index("注文者")
        #   line.force_encoding("UTF-8").match(reg3)
        #   goods ["name"]="#$1"
        # end

        # アイテム名を取得
        if line.force_encoding("UTF-8").index("商品名称")
          line.force_encoding("UTF-8").match(reg1)
          good_name = "#{$1}(#{$2})"
        end

        # 数量を取得してアイテム名をキーに，数量をバリューにしてハッシュに格納
        if line.force_encoding("UTF-8").index("数量")
          line.force_encoding("UTF-8").match(reg2)
          @parsed_items[good_name] = "#{$1}"
        end
      end
      # ファイルクローズ
      file.close

      # デバッグ出力
      # @parsed_items.each do|key,value|
      #   puts key.to_s+": "+value.to_s
      # end

      # パースしたデータをもとにアイテムエントリを作成
      @parsed_items.each do|key,value|
        #puts key.to_s+": "+value.to_s

        # 名前で重複を許さない場合
        # flag = Item.where(name: foodname).exists?
        # if flag == false

        # アイテム名で賞味期限データベースを検索して，
        # 賞味期限データが存在すればこれをもとに期限日を算出する
        start_date = Date.today.to_s
        end_date = Date.today.to_s
        freshness = Freshness.where(:name => key)
        if freshness
          tmp = Date.today + freshness
          end_date = tmp.to_s
        end

        # 新規アイテムを作成
        @touroku = Item.create(title: key,
                               user_id: current_user.id,
                               amount_at_a_time: value,
                               gram_at_a_time: 0,
                               price_at_a_time: 0,
                               price_at_one_amount: 0,
                               price_at_one_gram: 0,
                               start: start_date,
                               end: end_date,
                               allDay: true,
                               remaining_amount: value,
                               description: 説明を入力して下さい,
                               icon: false)
        if @touroku.save
          render text: "新規にデータを登録しました:#{new_name}"
        else
          render text: "新規データ登録に失敗しました:#{new_name}"
        end

        # else
        #   render text: "既にデータが存在しています: #{new_name}"
        # end
      end
    # メールファイルが見つからなかった場合
    rescue
      puts"the mail file is inexistence"
      #retry
    end
  end


  #=================================================================================================================================================
  # レシピ提案
  # acquire_recommended_recipes(queries) は検索したいアイテムを配列で渡してやることで
  # cookpadをOR検索してスクレイピングし，この結果をまとめて，レシピ構造体を要素に持つ配列として返す．
  # 一時的にテキストファイルに保存する機能も提供．

  # 構造体でデータ管理のためのクラス(モデル．だがrailsのモデルではない)を作成．
  # 定数として宣言するため，メソッドの内部では定義せずに外で定義すること

  # レシピ管理クラス
  # レシピ1つ分を表現する．
  # 複数のレシピがrecipe_listに格納される．
  # ingredientsにはIngredientインスタンスが要素の配列ingredient_listが入る
  Recipe = Struct.new(:id, :title, :amount, :ingredient_list, :url, :date)

  # レシピ食材管理クラス
  Ingredient = Struct.new(:id, :name, :amount)

  def acquire_recommended_recipes(queries)
    ##############################
    # Randomクラスの定義
    ##############################
    random = Random.new

    ###################################
    # 変数
    ###################################
    id_num = 1	# id設定用変数
    recipe_list = Array.new		# レシピ用配列
    #ingredient_list = Array.new	# 食材用配列

    ##############################
    # 読み込むURIの階層数の設定
    # 0 => 指定したURIのみ読み込む
    # 1(or more) => 指定したURIにあるlinkから1(or more)回のジャンプで辿れるURIも読み込む
    ##############################
    opts = { depth_limit: 1 }

    ##############################
    # 検索クエリを取得して1本の文字列にする
    # 配列で渡ってきたクエリを使う．
    # クエリが指定されて折らず空配列だった場合は「りんご+バナナ」で検索
    ##############################
    query = ""
    if (queries.length == 0)
      query = "りんご%20バナナ"			# デフォルト値
    else
      queries.each do |arg|
        query = query + "%20"		# クックパッド内蔵検索機能用
        #query = query + "+"		# Google検索機能用
        query = query + arg
      end
    end

    ###################################
    # りんごとバナナのOR検索URI例
    # http://cookpad.com/search/バナナ%20りんご
    ###################################
    uri = Addressable::URI.parse("http://cookpad.com/search/#{query}").normalize
    uri.query_values = {order: 'date', page: '1'}

    ##############################
    # Anemoneでクローラの起動
    # 引数1 => クロールしたいURI
    # 引数2 => 階層数の設定
    ##############################
    Anemone.crawl(uri.to_s, opts) do |anemone|
      ##############################
      # 料理詳細ページに対するスクレイピングの実行
      ##############################
      anemone.on_pages_like(%r{http://cookpad.com/recipe/[0-9]+}) do |page|
        ##############################
        # page.docでnokogiriインスタンスを取得し、
        # xpathで欲しい要素(ノード)を絞り込む
        ##############################
        page.doc.xpath("//div[@id='main']").each do |node|
          ##############################
          # レシピタイトルの抽出
          ##############################
          title = node.xpath(".//div[@id='recipe']/div[@id='recipe-main']/div[@id='recipe-title']/h1[contains(@class,'recipe-title')]//text()").to_s
          title = title.strip													# 文字列の前後に含まれる空白の削除

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_edit.html.slim
== render 'form'

app/views/items/_form.html.slim
div.main_content.clearfix
  /ページ遷移したくないので:remote => trueにしておく
  = form_for @item, :remote => true do |f|
    - if @item.errors.any?
      #error_explanation
        h2 = "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
        ul
          - @item.errors.full_messages.each do |message|
            li = message

    .actions = f.submit '編集を反映'
    table
      tbody
        tr
          td.left
            = f.label :食材名
          td.right
            = f.text_field :title, :size=>'40'
        tr
          td.left
            = f.label :購入単位の個数
          td.right
            = f.text_field :amount_at_a_time, :size=>'40'
        tr
          td.left
            = f.label :購入単位のグラム数
          td.right
            = f.text_field :gram_at_a_time, :size=>'40'
        tr
          td.left
            = f.label :購入単位の価格
          td.right
            = f.text_field :price_at_a_time, :size=>'40'
        tr
          td.left
            = f.label :個単位の価格
          td.right
            = f.text_field :price_at_one_amount, :size=>'40'
        tr
          td.left
            = f.label :グラム単位の価格
          td.right
            = f.text_field :price_at_one_gram, :size=>'40'
        tr
          td.left
            = f.label :購入日
          td.right
            = f.date_select :start, :size=>'40'
        tr
          td.left
            = f.label :賞味期限日
          td.right
            = f.date_select :end, :size=>'40'
        tr
          td.left
            = f.label :残数
          td.right
            = f.text_field :remaining_amount, :size=>'40'
        tr
          td.left
            = f.label :残グラム
          td.right
            = f.text_field :remaining_gram, :size=>'40'
        tr
          td.left
            = f.label :コメント
          td.right
            = f.text_area :description, :size=>'40x5'
        tr
          td.left
            = f.label :アイコン
          td.right
            = f.file_field :icon
            /= f.file_field :icon,accept: "image/jpeg"

div.div_button_container.clearfix
  div.div_button.button_edit
    = link_to 'キャンセル', { :controller => :items, :action => :show }, :remote => true
  div.div_button.button_destroy
    = link_to '食材を破棄', @item, data: {:confirm => '本当に破棄しますか？'}, :method => :delete, :remote => true

app/views/items/_show.html.slim
div.main_content.clearfix
  table
    tbody
      tr.item_icon
        td.icon_td colspan='2'
          = image_tag @item.icon.url, :class => 'item_icon'
      tr.item_title
        td.left
          strong 食材名:
        td.right
          = @item.title
      tr
        td.left
          strong 購入単位の個数:
        td.right
          = @item.amount_at_a_time
      tr
        td.left
          strong 購入単位のグラム数:
        td.right
          = @item.gram_at_a_time
      tr
        td.left
          strong 購入単位の価格:
        td.right
          = @item.price_at_a_time
      tr
        td.left
          strong 個単位の価格:
        td.right
          = @item.price_at_one_amount
      tr
        td.left
          strong グラム単位の価格:
        td.right
          = @item.price_at_one_gram
      tr
        td.left
          strong 購入日:
        td.right
          = @item.start
      tr
        td.left
          strong 賞味期限日:
        td.right
          = @item.end
      tr
        td.left
          strong 残数:
        td.right
          = @item.remaining_amount
      tr
        td.left
          strong 残グラム:
        td.right
          = @item.remaining_gram
      tr
        td.left
          strong コメント:
        td.right
          = @item.description
      /tr
        td.left
          strong アイコン:
        td.right
          /= @item.icon
          = image_tag @item.icon.url

div.div_button_container.clearfix
  div.div_button.button_recipe
    = link_to 'この食材でレシピを提案',
              { :controller => :items, :action => :show_recipes, :name => @item.title },
              :remote => true
  div.div_button.button_edit
    = link_to '編集',
              edit_item_path(@item),
              :remote => true
  div.div_button.button_destroy
    = link_to '破棄',
              @item,
              data: {:confirm => '本当に破棄しますか？'},
              :method => :delete,
              :remote => true

app/views/items/_show_recipes.html.slim
div.main_content.clearfix
  - @recipes.each do |recipe|
    table
      tbody
        /tr
          td.icon_td colspan='2'
            = image_tag @item.icon.url, :class => 'item_icon'
        tr.recipe_title
          td.left
            strong レシピ名:
          td.right
            = link_to recipe.title, recipe.url, :target => '_blank'
        /tr
          td.left
            strong url:
          td.right
            = link_to recipe.url
        - recipe.ingredient_list.each do |ingredient|
          tr
            td.left
              strong = ingredient.name
            td.right
              = ingredient.amount

  /div.div_button_container.clearfix
  /div.div_button.button_recipe
  /  = link_to 'この食材でレシピを提案', edit_item_path(@item), :remote => true
  /div.div_button.button_edit
  /  = link_to '編集', edit_item_path(@item), :remote => true
  /div.div_button.button_destroy
  /  = link_to '破棄', @item, data: {:confirm => '本当に破棄しますか？'}, :method => :delete, :remote => true

app/views/items/destroy.js.erb
//カレンダーを再描画
$('#calendar').fullCalendar('rendar');

// カレンダー用のデータを再取得
$('#calendar').fullCalendar('refetchEvents');

// 当該アイテムを削除したので詳細表示も消す
$("#right-column").html("");
$(".main_content").css("height", $("#right-column").height() - 180)

app/views/items/edit.html.slim
h1 食材の詳細情報を登録

== render 'form'

/= link_to 'Show', @item
/'|
/= link_to 'Back', items_path

app/views/items/edit.js.erb
//カレンダーを再描画
//$('#calendar').fullCalendar('rendar');

// カレンダー用のデータを再取得
//$('#calendar').fullCalendar('refetchEvents');

// 部分テンプレート(_show)を表示(前回の内容を消してから)
$("#right-column").html("");
$("#right-column").html("<%= j( render(:partial => 'edit') ) %>");
$(".main_content").css("height", $("#right-column").height() - 120)

app/views/items/index.html.slim
h1 Listing items

table
  thead
    tr
      th Title
      th User
      th Amount at a time
      th Gram at a time
      th Price at a time
      th Price at one amount
      th Price at one gram
      th Start
      th End
      th All day
      th Remaining amount
      th Remaining gram
      th Description
      th Icon
      th
      th
      th

  tbody
    - @items.each do |item|
      tr
        td = item.title
        td = item.user_id
        td = item.amount_at_a_time
        td = item.gram_at_a_time
        td = item.price_at_a_time
        td = item.price_at_one_amount
        td = item.price_at_one_gram
        td = item.start
        td = item.end
        td = item.allDay
        td = item.remaining_amount
        td = item.remaining_gram
        td = item.description
        td = item.icon
        td = link_to 'Show', item
        td = link_to 'Edit', edit_item_path(item)
        td = link_to 'Destroy', item, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Item', new_item_path

app/views/items/new.html.slim
h1 New item

== render 'form'

= link_to 'Back', items_path

app/views/items/show.html.slim
p#notice = notice

p
  strong 食材名:
  = @item.title
/p
  strong User id:
  = @item.user_id
p
  strong 購入単位の個数:
  = @item.amount_at_a_time
p
  strong 購入単位のグラム数:
  = @item.gram_at_a_time
p
  strong 購入単位の価格:
  = @item.price_at_a_time
p
  strong 個単位の価格:
  = @item.price_at_one_amount
p
  strong グラム単位の価格:
  = @item.price_at_one_gram
p
  strong 購入日:
  = @item.start
p
  strong 賞味期限日:
  = @item.end
/p
  strong All day:
  = @item.allDay
p
  strong 残数:
  = @item.remaining_amount
p
  strong 残グラム:
  = @item.remaining_gram
p
  strong コメント:
  = @item.description
/p
  strong アイコン:
  = @item.icon

p
  = link_to 'この食材を破棄', @item, data: {:confirm => '本当に破棄しますか？'}, :method => :delete

/= link_to 'Edit', edit_item_path(@item)
/'|
/= link_to 'Back', items_path

app/views/items/show.js.erb
//カレンダーを再描画
//$('#calendar').fullCalendar('rendar');

// カレンダー用のデータを再取得
//$('#calendar').fullCalendar('refetchEvents');

// 部分テンプレート(_show)を表示(前回の内容を消してから)
$("#right-column").html("");
$("#right-column").html("<%= j( render(:partial => 'show') ) %>");
$(".main_content").css("height", $("#right-column").height() - 180)

app/views/items/show_recipes.js.erb
// 部分テンプレート(_show)を表示(前回の内容を消してから)
$("#right-column").html("");
$("#right-column").html("<%= j( render(:partial => 'show_recipes') ) %>");
$(".main_content").css("height", $("#right-column").height())

app/views/items/update.js.erb
//カレンダーを再描画
$('#calendar').fullCalendar('rendar');

// カレンダー用のデータを再取得
$('#calendar').fullCalendar('refetchEvents');

// 部分テンプレート(_show)を表示(前回の内容を消してから)
$("#right-column").html("");
$("#right-column").html("<%= j( render(:partial => 'show') ) %>");
$(".main_content").css("height", $("#right-column").height() - 180)