config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'home/index' # bundle exec rails g controller home indexすると自動で追加される
  get 'index' => 'home#index' # localhost:3000/index や localhost:3000/index.html は home#index に飛ばす

  devise_for :users

  get 'items/current_user_id' => 'items#current_user_id'

  get 'items/index_by_user' => 'items#index_by_user'
  get 'items/show_recipes' => 'items#show_recipes'
  resources :items

  get 'freshnesses/freshness_by_name' => 'freshnesses#freshness_by_name'
  resources :freshnesses

end

app/controllers/freshnesses_controller.rb
class FreshnessesController < ApplicationController
  before_action :set_freshness, only: [:show, :edit, :update, :destroy]

  # GET /freshnesses
  # GET /freshnesses.json
  def index
    @freshnesses = Freshness.all
  end

  # GET /freshnesses/1
  # GET /freshnesses/1.json
  def show
    # @freshness = Freshness.find(params[:id])
    # respond_to do |format|
    #   format.html { render :show }
    #   format.json { render :show, status: :ok, location: @freshness }
    # end
  end

  # GET /freshnesses/new
  def new
    @freshness = Freshness.new
  end

  # GET /freshnesses/1/edit
  def edit
  end

  # POST /freshnesses
  # POST /freshnesses.json
  def create
    @freshness = Freshness.new(freshness_params)

    respond_to do |format|
      if @freshness.save
        format.html { redirect_to @freshness, notice: 'Freshness was successfully created.' }
        format.json { render :show, status: :created, location: @freshness }
      else
        format.html { render :new }
        format.json { render json: @freshness.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /freshnesses/1
  # PATCH/PUT /freshnesses/1.json
  def update
    respond_to do |format|
      if @freshness.update(freshness_params)
        format.html { redirect_to @freshness, notice: 'Freshness was successfully updated.' }
        format.json { render :show, status: :ok, location: @freshness }
      else
        format.html { render :edit }
        format.json { render json: @freshness.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /freshnesses/1
  # DELETE /freshnesses/1.json
  def destroy
    @freshness.destroy
    respond_to do |format|
      format.html { redirect_to freshnesses_url, notice: 'Freshness was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #=================================================================================================================================================
  # アイテム名から賞味期間をとってくる
  def freshness_by_name
    @freshness = 0
    if Freshness.where(:name => params['name']).exists?
      @freshness = Freshness.where(:name => params['name']).first().freshness;
    end
    respond_to do |format|
      format.json { render :json => @freshness }
      # format.json { render :json => @freshness, location: @freshness }
    end
  end


  #=================================================================================================================================================
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_freshness
      @freshness = Freshness.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def freshness_params
      params.require(:freshness).permit(:name, :freshness)
    end
end

app/helpers/freshnesses_helper.rb
module FreshnessesHelper
end

app/views/freshnesses/_form.html.slim
= form_for @freshness do |f|
  - if @freshness.errors.any?
    #error_explanation
      h2 = "#{pluralize(@freshness.errors.count, "error")} prohibited this freshness from being saved:"
      ul
        - @freshness.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :freshness
    = f.number_field :freshness
  .actions = f.submit

app/views/freshnesses/edit.html.slim
h1 Editing freshness

== render 'form'

= link_to 'Show', @freshness
'|
= link_to 'Back', freshnesses_path

app/views/freshnesses/index.html.slim
h1 Listing freshnesses

table
  thead
    tr
      th Name
      th Freshness
      th
      th
      th

  tbody
    - @freshnesses.each do |freshness|
      tr
        td = freshness.name
        td = freshness.freshness
        td = link_to 'Show', freshness
        td = link_to 'Edit', edit_freshness_path(freshness)
        td = link_to 'Destroy', freshness, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Freshness', new_freshness_path

app/views/freshnesses/new.html.slim
h1 New freshness

== render 'form'

= link_to 'Back', freshnesses_path

app/views/freshnesses/show.html.slim
p#notice = notice

p
  strong Name:
  = @freshness.name
p
  strong Freshness:
  = @freshness.freshness

= link_to 'Edit', edit_freshness_path(@freshness)
'|
= link_to 'Back', freshnesses_path